USE accountsbase;
ALTER TABLE employees
 ADD COLUMN employee_number VARCHAR(30) NULL UNIQUE AFTER user_id,
 ADD COLUMN personal_email VARCHAR(120) NULL AFTER email,
 ADD COLUMN alternate_phone VARCHAR(30) NULL AFTER phone,
 ADD COLUMN date_of_birth DATE NULL AFTER alternate_phone,
 ADD COLUMN gender VARCHAR(30) NULL AFTER date_of_birth,
 ADD COLUMN marital_status VARCHAR(30) NULL AFTER gender,
 ADD COLUMN address TEXT NULL AFTER marital_status,
 ADD COLUMN city VARCHAR(80) NULL AFTER address,
 ADD COLUMN state VARCHAR(80) NULL AFTER city,
 ADD COLUMN postal_code VARCHAR(20) NULL AFTER state,
 ADD COLUMN country VARCHAR(80) NULL AFTER postal_code,
 ADD COLUMN emergency_contact_name VARCHAR(120) NULL AFTER country,
 ADD COLUMN emergency_contact_relationship VARCHAR(60) NULL AFTER emergency_contact_name,
 ADD COLUMN emergency_contact_phone VARCHAR(30) NULL AFTER emergency_contact_relationship,
 ADD COLUMN department VARCHAR(100) NULL AFTER designation,
 ADD COLUMN employment_type ENUM('full_time','part_time','contract','intern','temporary') NOT NULL DEFAULT 'full_time' AFTER department,
 ADD COLUMN work_location VARCHAR(120) NULL AFTER employment_type,
 ADD COLUMN manager_name VARCHAR(120) NULL AFTER work_location,
 ADD COLUMN probation_end_date DATE NULL AFTER joined_date,
 ADD COLUMN end_date DATE NULL AFTER probation_end_date,
 ADD COLUMN bank_name VARCHAR(120) NULL AFTER end_date,
 ADD COLUMN bank_account_name VARCHAR(120) NULL AFTER bank_name,
 ADD COLUMN bank_account_number VARCHAR(80) NULL AFTER bank_account_name,
 ADD COLUMN bank_routing_number VARCHAR(80) NULL AFTER bank_account_number,
 ADD COLUMN tax_id VARCHAR(80) NULL AFTER bank_routing_number,
 ADD COLUMN national_id VARCHAR(80) NULL AFTER tax_id,
 ADD COLUMN notes TEXT NULL AFTER national_id,
 ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;
