<?php
require_once __DIR__.'/app.php';

function render_invoice_document(PDO $pdo,array $invoice,array $lines,array $template,bool $forPdf=false):string
{
    $labels=json_decode($template['column_labels']??'{}',true)?:[];$blocks=json_decode($template['block_order']??'[]',true)?:['company','invoice_meta','customer','items','totals','bank','notes'];$primary=preg_match('/^#[0-9a-f]{6}$/i',$template['primary_color']??'')?$template['primary_color']:'#2563eb';$accent=preg_match('/^#[0-9a-f]{6}$/i',$template['accent_color']??'')?$template['accent_color']:'#0f172a';$font=in_array($template['font_family']??'Helvetica',['Helvetica','Arial','Times New Roman','Georgia','Courier New'],true)?$template['font_family']:'Helvetica';$symbol=$invoice['symbol'];if($forPdf&&!preg_match('/^[\x20-\x7E]+$/',$symbol))$symbol=$invoice['currency_code'].' ';$balance=$invoice['grand_total']-$invoice['amount_paid'];$logo='';if(!empty($template['logo_path'])){$file=dirname(__DIR__).'/'.$template['logo_path'];if(is_file($file))$logo=$forPdf?'file://'.$file:'../../'.$template['logo_path'];}
    ob_start();?>
    <section id="invoiceDocument" style="font-family:<?=h($font)?>;background:#fff;color:#1e293b;padding:<?= $forPdf?'18px':'32px' ?>;font-size:13px;line-height:1.45">
    <?php foreach($blocks as $block):if($block==='company'):?><div style="display:table;width:100%;border-bottom:2px solid <?=$accent?>;padding-bottom:18px;margin-bottom:20px"><div style="display:table-cell;vertical-align:top"><?php if($logo):?><img src="<?=h($logo)?>" style="max-height:60px;max-width:180px;margin-bottom:8px"><?php endif;?><h1 style="font-size:24px;margin:0"><?=h(setting($pdo,'company_name','AccountsBase'))?></h1><div style="color:#64748b;white-space:pre-line"><?=h(setting($pdo,'company_address'))?><br><?=h(setting($pdo,'company_email'))?> <?=h(setting($pdo,'company_phone'))?></div></div><div style="display:table-cell;text-align:right;vertical-align:top"><div style="font-size:32px;color:<?=$primary?>;font-weight:bold">INVOICE</div><strong style="font-size:17px"><?=h($invoice['invoice_number'])?></strong><br><span style="display:inline-block;margin-top:6px;padding:4px 10px;background:#f1f5f9;border-radius:10px;font-size:10px;font-weight:bold"><?=h(strtoupper($invoice['status']))?></span></div></div>
    <?php elseif($block==='invoice_meta'):?><div style="text-align:right;margin-bottom:20px"><strong>Issued:</strong> <?=h(date('M j, Y',strtotime($invoice['issue_date'])))?> &nbsp; <strong>Due:</strong> <?=h(date('M j, Y',strtotime($invoice['due_date'])))?> &nbsp; <strong>Currency:</strong> <?=h($invoice['currency_code'])?></div>
    <?php elseif($block==='customer'):?><div style="margin-bottom:22px"><div style="font-size:10px;color:#64748b;font-weight:bold">BILL TO</div><strong style="font-size:17px"><?=h($invoice['company_name'])?></strong><div><?=h($invoice['contact_person'])?><br><?=h($invoice['email'])?><br><span style="white-space:pre-line"><?=h($invoice['billing_address'])?></span></div></div>
    <?php elseif($block==='items'):?><table style="width:100%;border-collapse:collapse;margin-bottom:20px"><thead><tr style="background:<?=$accent?>;color:white"><th style="text-align:left;padding:9px"><?=h($labels['description']??'Description')?></th><th style="text-align:right;padding:9px"><?=h($labels['quantity']??'Qty')?></th><th style="text-align:right;padding:9px"><?=h($labels['unit_price']??'Rate')?></th><th style="text-align:right;padding:9px"><?=h($labels['tax']??'Tax')?></th><th style="text-align:right;padding:9px"><?=h($labels['amount']??'Amount')?></th></tr></thead><tbody><?php foreach($lines as $line):?><tr style="border-bottom:1px solid #e2e8f0"><td style="padding:9px"><?=h($line['description'])?></td><td style="padding:9px;text-align:right"><?=h((string)$line['quantity'])?></td><td style="padding:9px;text-align:right"><?=h($symbol).number_format($line['unit_price'],2)?></td><td style="padding:9px;text-align:right"><?=h((string)$line['tax_rate'])?>%</td><td style="padding:9px;text-align:right;font-weight:bold"><?=h($symbol).number_format($line['line_total'],2)?></td></tr><?php endforeach;?></tbody></table>
    <?php elseif($block==='totals'):?><div style="margin-left:55%;margin-bottom:22px"><div style="display:table;width:100%;padding:4px"><span style="display:table-cell">Subtotal</span><strong style="display:table-cell;text-align:right"><?=h($symbol).number_format($invoice['subtotal'],2)?></strong></div><div style="display:table;width:100%;padding:4px"><span style="display:table-cell">Tax</span><strong style="display:table-cell;text-align:right"><?=h($symbol).number_format($invoice['tax_total'],2)?></strong></div><div style="display:table;width:100%;padding:9px;background:<?=$primary?>;color:white"><strong style="display:table-cell">Total</strong><strong style="display:table-cell;text-align:right"><?=h($symbol).number_format($invoice['grand_total'],2)?></strong></div><div style="display:table;width:100%;padding:5px"><span style="display:table-cell">Paid</span><strong style="display:table-cell;text-align:right"><?=h($symbol).number_format($invoice['amount_paid'],2)?></strong></div><div style="display:table;width:100%;padding:5px"><strong style="display:table-cell">Balance due</strong><strong style="display:table-cell;text-align:right"><?=h($symbol).number_format($balance,2)?></strong></div></div>
    <?php elseif($block==='bank'&&!empty($template['bank_details'])):?><div style="border-top:1px solid #e2e8f0;padding-top:12px;margin-bottom:16px"><strong>Payment details</strong><div style="white-space:pre-line;color:#475569"><?=h($template['bank_details'])?></div></div>
    <?php elseif($block==='custom'&&!empty($template['custom_details'])):?><div style="border:1px solid #e2e8f0;padding:12px;margin-bottom:16px;white-space:pre-line"><?=h($template['custom_details'])?></div>
    <?php elseif($block==='notes'):?><div style="border-top:1px solid #e2e8f0;padding-top:12px;color:#64748b;white-space:pre-line"><?=h($invoice['notes'])?><?=($invoice['notes']&&$invoice['terms'])?"\n\n":''?><?=h($invoice['terms'])?><?php if(!empty($template['footer_text'])):?>

<?=h($template['footer_text'])?><?php endif;?></div><?php endif;endforeach;?></section>
    <?php return (string)ob_get_clean();
}
