<?php
require_once '../config/db.php';$start=$_GET['start']??date('Y-m-01');$end=$_GET['end']??date('Y-m-d');$params=['start'=>$start,'end'=>$end];
$queries=[
 'Customer receipts'=>["SELECT COALESCE(SUM(amount),0) FROM payments WHERE payment_type='inbound' AND payment_date BETWEEN :start AND :end",'in'],
 'Operating expenses'=>['SELECT COALESCE(SUM(amount),0) FROM expenses WHERE expense_date BETWEEN :start AND :end','out'],
 'Cleared payables'=>["SELECT COALESCE(SUM(amount),0) FROM debits WHERE status='cleared' AND debit_date BETWEEN :start AND :end",'out'],
 'Payroll'=>["SELECT COALESCE(SUM(net_payable),0) FROM payslips WHERE status='paid' AND payment_date BETWEEN :start AND :end",'out'],
 'Investments purchased'=>['SELECT COALESCE(SUM(amount),0) FROM investments WHERE investment_date BETWEEN :start AND :end','out'],
 'Loan repayments'=>['SELECT COALESCE(SUM(amount),0) FROM loan_payments WHERE payment_date BETWEEN :start AND :end','out']];
$rows=[];$in=0;$out=0;foreach($queries as $label=>[$sql,$type]){$s=$pdo->prepare($sql);$s->execute($params);$amount=(float)$s->fetchColumn();$rows[]=[$label,$type,$amount];$type==='in'?$in+=$amount:$out+=$amount;}$opening=(float)$pdo->query('SELECT COALESCE(SUM(current_balance),0) FROM accounts')->fetchColumn()-$in+$out;require_once 'includes/header.php';require_once 'includes/sidebar.php';
?>
<main class="flex-1 h-screen overflow-y-auto app-scroll"><header class="bg-white border-b px-5 md:px-8 py-5 flex items-center gap-4 sticky top-0 z-10"><button data-sidebar-toggle class="lg:hidden text-2xl">☰</button><div><h2 class="text-2xl font-bold">Cash flow</h2><p class="text-sm text-slate-500">Where your cash came from and where it went</p></div></header><div class="p-5 md:p-8 max-w-5xl mx-auto"><form class="bg-white border rounded-xl p-4 flex flex-wrap gap-4 items-end mb-6"><label class="text-sm">From<input type="date" name="start" value="<?=h($start)?>" class="block border rounded-lg px-3 py-2"></label><label class="text-sm">To<input type="date" name="end" value="<?=h($end)?>" class="block border rounded-lg px-3 py-2"></label><button class="brand-bg text-white px-5 py-2 rounded-lg">Apply</button></form><div class="grid sm:grid-cols-3 gap-4 mb-6"><div class="bg-emerald-50 border border-emerald-200 rounded-xl p-5"><p class="text-sm text-emerald-700">Cash in</p><p class="text-2xl font-black text-emerald-800"><?=money($pdo,$in)?></p></div><div class="bg-rose-50 border border-rose-200 rounded-xl p-5"><p class="text-sm text-rose-700">Cash out</p><p class="text-2xl font-black text-rose-800"><?=money($pdo,$out)?></p></div><div class="bg-slate-950 text-white rounded-xl p-5"><p class="text-sm text-slate-400">Net movement</p><p class="text-2xl font-black"><?=money($pdo,$in-$out)?></p></div></div><section class="bg-white border rounded-2xl p-7"><h3 class="text-xl font-bold mb-5">Cash flow statement</h3><div class="flex justify-between py-3 border-b"><span>Estimated opening cash</span><strong><?=money($pdo,$opening)?></strong></div><?php foreach($rows as [$label,$type,$amount]):?><div class="flex justify-between py-3 border-b"><span><?=h($label)?></span><strong class="<?=$type==='in'?'text-emerald-700':'text-rose-700'?>"><?=$type==='in'?'+':'-'?><?=money($pdo,$amount)?></strong></div><?php endforeach;?><div class="flex justify-between py-5 text-xl"><strong>Closing cash balance</strong><strong><?=money($pdo,$opening+$in-$out)?></strong></div></section></div></main><?php require_once 'includes/footer.php';?>
