<?php
require_once '../config/db.php'; require_once 'includes/header.php'; require_once 'includes/sidebar.php';
$metrics=['balance'=>(float)$pdo->query('SELECT COALESCE(SUM(current_balance),0) FROM accounts WHERE is_active=1')->fetchColumn(),'revenue'=>(float)$pdo->query("SELECT COALESCE(SUM(amount_paid),0) FROM invoices WHERE status<>'voided'")->fetchColumn(),'expenses'=>(float)$pdo->query('SELECT COALESCE(SUM(amount),0) FROM expenses')->fetchColumn(),'receivable'=>(float)$pdo->query("SELECT COALESCE(SUM(grand_total-amount_paid),0) FROM invoices WHERE status IN ('sent','unpaid','partial')")->fetchColumn(),'payable'=>(float)$pdo->query("SELECT COALESCE(SUM(amount),0) FROM debits WHERE status='pending'")->fetchColumn()];
$recent=$pdo->query("SELECT i.id,i.invoice_number,i.issue_date,i.grand_total,i.status,c.company_name FROM invoices i JOIN contacts c ON c.id=i.contact_id ORDER BY i.created_at DESC LIMIT 7")->fetchAll();
$monthly=$pdo->query("SELECT DATE_FORMAT(issue_date,'%Y-%m') month,COALESCE(SUM(amount_paid),0) amount FROM invoices WHERE issue_date>=DATE_SUB(CURDATE(),INTERVAL 5 MONTH) GROUP BY month ORDER BY month")->fetchAll();$maxMonth=max(array_column($monthly,'amount')?:[1]);
?>
<main class="flex-1 h-screen overflow-y-auto app-scroll"><header class="bg-white border-b px-5 md:px-8 py-5 flex items-center justify-between sticky top-0 z-10"><div class="flex items-center gap-4"><button data-sidebar-toggle class="lg:hidden text-2xl">☰</button><div><h2 class="text-2xl font-bold">Financial overview</h2><p class="text-sm text-slate-500"><?=h(date('l, F j, Y'))?></p></div></div><a href="invoice/create_invoice.php" class="brand-bg text-white px-4 py-2.5 rounded-lg font-semibold text-sm">+ New invoice</a></header>
<div class="p-5 md:p-8 max-w-7xl mx-auto"><div class="grid sm:grid-cols-2 xl:grid-cols-5 gap-4 mb-7">
<?php foreach([['Available cash',$metrics['balance'],'text-blue-700','bg-blue-50'],['Collected revenue',$metrics['revenue'],'text-emerald-700','bg-emerald-50'],['Operating expenses',$metrics['expenses'],'text-rose-700','bg-rose-50'],['Receivables',$metrics['receivable'],'text-amber-700','bg-amber-50'],['Pending payables',$metrics['payable'],'text-violet-700','bg-violet-50']] as [$label,$value,$color,$bg]):?><div class="bg-white border rounded-2xl p-5 shadow-sm"><div class="w-9 h-9 rounded-lg <?=$bg?> mb-4"></div><p class="text-xs font-bold uppercase tracking-wide text-slate-500"><?=h($label)?></p><p class="money text-2xl font-extrabold mt-1 <?=$color?>"><?=money($pdo,$value)?></p></div><?php endforeach;?></div>
<div class="grid xl:grid-cols-3 gap-7"><section class="xl:col-span-2 bg-white border rounded-2xl shadow-sm overflow-hidden"><div class="p-5 border-b flex justify-between"><div><h3 class="font-bold text-lg">Recent invoices</h3><p class="text-sm text-slate-500">Latest customer billing activity</p></div><a href="invoice/invoices.php" class="brand-text font-semibold text-sm">View all →</a></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-slate-50 text-slate-500"><tr><th class="text-left px-5 py-3">Invoice</th><th class="text-left px-5 py-3">Customer</th><th class="text-right px-5 py-3">Total</th><th class="text-left px-5 py-3">Status</th></tr></thead><tbody class="divide-y">
<?php foreach($recent as $inv):?><tr class="hover:bg-slate-50"><td class="px-5 py-4"><a class="font-bold brand-text" href="invoice/view_invoice.php?id=<?=$inv['id']?>"><?=h($inv['invoice_number'])?></a><p class="text-xs text-slate-400"><?=h(date('M j',strtotime($inv['issue_date'])))?></p></td><td class="px-5 py-4"><?=h($inv['company_name'])?></td><td class="px-5 py-4 text-right money font-semibold"><?=money($pdo,$inv['grand_total'])?></td><td class="px-5 py-4"><span class="px-2.5 py-1 rounded-full text-xs font-bold bg-slate-100"><?=h(ucfirst($inv['status']))?></span></td></tr><?php endforeach;?><?php if(!$recent):?><tr><td colspan="4" class="p-10 text-center text-slate-500">No invoices yet. Create your first invoice to start tracking revenue.</td></tr><?php endif;?></tbody></table></div></section>
<aside class="space-y-7"><section class="bg-slate-950 text-white rounded-2xl p-6 shadow-sm"><p class="text-sm text-slate-400">Net operating position</p><p class="text-3xl font-black mt-2"><?=money($pdo,$metrics['revenue']-$metrics['expenses'])?></p><p class="text-sm text-slate-400 mt-2">Collected revenue minus operating expenses</p><a href="report_genaretor.php" class="inline-block mt-5 text-sm font-bold brand-text">Open reports →</a></section><section class="bg-white border rounded-2xl p-6 shadow-sm"><h3 class="font-bold">Revenue trend</h3><div class="h-40 flex items-end gap-3 mt-5"><?php foreach($monthly as $m):$height=max(8,($m['amount']/$maxMonth)*100);?><div class="flex-1 text-center"><div class="brand-bg rounded-t-md mx-auto" style="height:<?=$height?>px"></div><span class="text-[10px] text-slate-400"><?=h(date('M',strtotime($m['month'].'-01')))?></span></div><?php endforeach;?><?php if(!$monthly):?><p class="text-sm text-slate-400 self-center">Chart will appear after payments are recorded.</p><?php endif;?></div></section></aside></div></div></main>
<?php require_once 'includes/footer.php';?>
