<?php
require_once '../../config/db.php'; require_once '../includes/header.php'; require_once '../includes/sidebar.php';
$status=$_GET['status']??'';$q=trim((string)($_GET['q']??''));$params=[];$where=[];
if(in_array($status,['draft','sent','unpaid','partial','paid','voided'],true)){$where[]='i.status=?';$params[]=$status;}
if($q!==''){$where[]='(i.invoice_number LIKE ? OR c.company_name LIKE ?)';$params[]='%'.$q.'%';$params[]='%'.$q.'%';}
$sql="SELECT i.*,c.company_name,cur.symbol FROM invoices i JOIN contacts c ON c.id=i.contact_id JOIN currencies cur ON cur.code=i.currency_code".($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY i.created_at DESC';$stmt=$pdo->prepare($sql);$stmt->execute($params);$invoices=$stmt->fetchAll();
$totals=$pdo->query("SELECT COUNT(*) total,COALESCE(SUM(grand_total),0) billed,COALESCE(SUM(amount_paid),0) paid,COALESCE(SUM(grand_total-amount_paid),0) due FROM invoices WHERE status<>'voided'")->fetch();
?>
<main class="flex-1 h-screen overflow-y-auto app-scroll"><header class="bg-white border-b px-5 md:px-8 py-5 flex justify-between items-center sticky top-0 z-10"><div class="flex gap-4 items-center"><button data-sidebar-toggle class="lg:hidden text-2xl">☰</button><div><h2 class="text-2xl font-bold">Invoices & payments</h2><p class="text-sm text-slate-500">Manage billing and collections</p></div></div><a href="create_invoice.php" class="brand-bg text-white px-4 py-2.5 rounded-lg font-semibold">+ Create invoice</a></header>
<div class="p-5 md:p-8 max-w-7xl mx-auto"><div class="grid sm:grid-cols-3 gap-4 mb-6"><?php foreach([['Total billed',$totals['billed']],['Collected',$totals['paid']],['Outstanding',$totals['due']]] as [$l,$v]):?><div class="bg-white border rounded-xl p-5"><p class="text-sm text-slate-500"><?=h($l)?></p><p class="text-2xl font-extrabold money mt-1"><?=money($pdo,$v)?></p></div><?php endforeach;?></div>
<div class="bg-white border rounded-2xl shadow-sm overflow-hidden"><form class="p-4 border-b flex flex-wrap gap-3"><input name="q" value="<?=h($q)?>" placeholder="Search invoice or customer" class="border rounded-lg px-3 py-2 flex-1 min-w-52"><select name="status" class="border rounded-lg px-3 py-2 bg-white"><option value="">All statuses</option><?php foreach(['unpaid','partial','paid','draft','sent','voided'] as $s):?><option <?=$status===$s?'selected':''?> value="<?=$s?>"><?=h(ucfirst($s))?></option><?php endforeach;?></select><button class="bg-slate-900 text-white px-5 py-2 rounded-lg">Filter</button></form>
<div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-slate-50 text-slate-500"><tr><th class="text-left p-4">Invoice</th><th class="text-left p-4">Customer</th><th class="text-left p-4">Due</th><th class="text-right p-4">Total</th><th class="text-right p-4">Balance</th><th class="text-left p-4">Status</th><th class="p-4"></th></tr></thead><tbody class="divide-y"><?php foreach($invoices as $inv):?><tr class="hover:bg-slate-50"><td class="p-4"><a href="view_invoice.php?id=<?=$inv['id']?>" class="font-bold brand-text"><?=h($inv['invoice_number'])?></a><p class="text-xs text-slate-400"><?=h(date('M j, Y',strtotime($inv['issue_date'])))?></p></td><td class="p-4 font-medium"><?=h($inv['company_name'])?></td><td class="p-4 <?=strtotime($inv['due_date'])<time()&&$inv['status']!=='paid'?'text-rose-600 font-semibold':''?>"><?=h(date('M j, Y',strtotime($inv['due_date'])))?></td><td class="p-4 text-right money"><?=h($inv['symbol']).number_format($inv['grand_total'],2)?></td><td class="p-4 text-right money font-bold"><?=h($inv['symbol']).number_format($inv['grand_total']-$inv['amount_paid'],2)?></td><td class="p-4"><span class="bg-slate-100 rounded-full px-2.5 py-1 text-xs font-bold"><?=h(ucfirst($inv['status']))?></span></td><td class="p-4 text-right"><a href="view_invoice.php?id=<?=$inv['id']?>" class="brand-text font-semibold">Open</a></td></tr><?php endforeach;?><?php if(!$invoices):?><tr><td colspan="7" class="text-center p-12 text-slate-500">No invoices match this view.</td></tr><?php endif;?></tbody></table></div></div></div></main>
<?php require_once '../includes/footer.php';?>
